baseURL = 'https://cors-simulator-dev.tomgregory.com/'
languageCode = 'en-gb'
title = 'CORS Simulator'
[params]
    apiBaseURL = "https://api.cors-simulator-dev.tomgregory.com/"
    assetsBaseURL = "https://assets.cors-simulator-dev.tomgregory.com/"