baseURL = 'https://corssimulator-dev.tomgregory.com/'
languageCode = 'en-gb'
title = 'CORS Simulator'
[params]
    apiBaseURL = "https://api.corssimulator-dev.tomgregory.com/"
    assetsBaseURL = "https://assets.corssimulator-dev.tomgregory.com/"