service: server
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs12.x
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /get-without-cors
          method: get
