service: server
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs12.x
functions:
  get-without-cors:
    handler: get-without-cors.hello
    events:
      - httpApi:
          path: /get-without-cors
          method: get
