service: server
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs12.x
params:
  default:
    s3BucketName: tomgregory-cors-examples
plugins:
  - serverless-s3-sync
custom:
  s3Sync:
    - bucketName: ${param:s3BucketName}
      localDir: assets/
functions:
  get-without-cors:
    handler: without-cors/get.handler
    events:
      - httpApi:
          path: /get-without-cors
          method: get
  post-without-cors:
    handler: without-cors/post.handler
    events:
      - httpApi:
          path: /post-without-cors
          method: post
resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${param:s3BucketName}