name: CORS Simulator
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.107.0'
    - name: Build website
      run: hugo -s website
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::299404798587:role/tomgregory-site-CORSSimulatorGitHubRole-KEZEJM5EIFFY
        aws-region: eu-west-1      